import type { Metadata } from 'next'
import './globals.css'
import { Lato } from 'next/font/google'

const inter = Lato({
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'PrimeBlock',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
